version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - export GOPATH=/go
      - export CODEBUILD_ROOT=`pwd`
      - cd signer
      - go test
  post_build:
    commands:
      - echo Build completed on `date`
